# Generated by Django 3.2.6 on 2021-09-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('procesador', models.CharField(max_length=120)),
                ('ram', models.CharField(max_length=120)),
                ('almacenamiento', models.CharField(max_length=120)),
                ('monitor', models.CharField(max_length=120)),
                ('teclado', models.CharField(max_length=120)),
                ('mouse', models.CharField(max_length=120)),
                ('printer1', models.CharField(max_length=120)),
                ('printer2', models.CharField(max_length=120)),
                ('estado', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
    ]
