# Generated by Django 3.2.6 on 2021-09-01 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0002_auto_20210827_0912'),
        ('area', '0001_initial'),
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomodel',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.areamodel'),
        ),
        migrations.AddField(
            model_name='equipomodel',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sedemodel'),
        ),
    ]
