# Generated by Django 3.2.6 on 2021-08-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sedemodel',
            options={'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelTable(
            name='sedemodel',
            table='sedes',
        ),
    ]
